# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'newfastdlgui.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1024, 680)
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.gridLayout_5 = QtGui.QGridLayout(self.centralWidget)
        self.gridLayout_5.setMargin(11)
        self.gridLayout_5.setSpacing(6)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.progressBar = QtGui.QProgressBar(self.centralWidget)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.gridLayout_5.addWidget(self.progressBar, 2, 0, 1, 1)
        self.runSync = QtGui.QPushButton(self.centralWidget)
        self.runSync.setObjectName(_fromUtf8("runSync"))
        self.gridLayout_5.addWidget(self.runSync, 4, 0, 1, 1)
        self.mainTextWindow = QtGui.QTextBrowser(self.centralWidget)
        self.mainTextWindow.setAcceptDrops(False)
        self.mainTextWindow.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.mainTextWindow.setObjectName(_fromUtf8("mainTextWindow"))
        self.gridLayout_5.addWidget(self.mainTextWindow, 0, 0, 1, 1)
        self.groupBox = QtGui.QGroupBox(self.centralWidget)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setMargin(11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.sourceDirBtn = QtGui.QPushButton(self.groupBox)
        self.sourceDirBtn.setObjectName(_fromUtf8("sourceDirBtn"))
        self.gridLayout.addWidget(self.sourceDirBtn, 0, 0, 1, 1)
        self.sourceDirDisplay = QtGui.QLineEdit(self.groupBox)
        self.sourceDirDisplay.setReadOnly(True)
        self.sourceDirDisplay.setObjectName(_fromUtf8("sourceDirDisplay"))
        self.gridLayout.addWidget(self.sourceDirDisplay, 0, 1, 1, 1)
        self.destDirBtn = QtGui.QPushButton(self.groupBox)
        self.destDirBtn.setObjectName(_fromUtf8("destDirBtn"))
        self.gridLayout.addWidget(self.destDirBtn, 1, 0, 1, 1)
        self.destDirDisplay = QtGui.QLineEdit(self.groupBox)
        self.destDirDisplay.setReadOnly(True)
        self.destDirDisplay.setObjectName(_fromUtf8("destDirDisplay"))
        self.gridLayout.addWidget(self.destDirDisplay, 1, 1, 1, 1)
        self.excludeListBtn = QtGui.QPushButton(self.groupBox)
        self.excludeListBtn.setObjectName(_fromUtf8("excludeListBtn"))
        self.gridLayout.addWidget(self.excludeListBtn, 2, 0, 1, 1)
        self.excludeListDisplay = QtGui.QLineEdit(self.groupBox)
        self.excludeListDisplay.setReadOnly(True)
        self.excludeListDisplay.setObjectName(_fromUtf8("excludeListDisplay"))
        self.gridLayout.addWidget(self.excludeListDisplay, 2, 1, 1, 1)
        self.runSync.raise_()
        self.excludeListBtn.raise_()
        self.destDirBtn.raise_()
        self.sourceDirBtn.raise_()
        self.excludeListDisplay.raise_()
        self.sourceDirDisplay.raise_()
        self.destDirDisplay.raise_()
        self.excludeListBtn.raise_()
        self.destDirBtn.raise_()
        self.sourceDirBtn.raise_()
        self.excludeListDisplay.raise_()
        self.sourceDirDisplay.raise_()
        self.destDirDisplay.raise_()
        self.gridLayout_5.addWidget(self.groupBox, 3, 0, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(self.centralWidget)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_4.setMargin(11)
        self.gridLayout_4.setSpacing(6)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_2 = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_4.addWidget(self.label_2, 0, 5, 1, 1)
        self.syncThreads = QtGui.QSpinBox(self.groupBox_2)
        self.syncThreads.setMaximumSize(QtCore.QSize(50, 16777215))
        self.syncThreads.setProperty("value", 10)
        self.syncThreads.setObjectName(_fromUtf8("syncThreads"))
        self.gridLayout_4.addWidget(self.syncThreads, 0, 6, 1, 1)
        self.bZipEnable = QtGui.QCheckBox(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bZipEnable.sizePolicy().hasHeightForWidth())
        self.bZipEnable.setSizePolicy(sizePolicy)
        self.bZipEnable.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.bZipEnable.setChecked(True)
        self.bZipEnable.setObjectName(_fromUtf8("bZipEnable"))
        self.gridLayout_4.addWidget(self.bZipEnable, 0, 2, 1, 1)
        self.label = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_4.addWidget(self.label, 0, 0, 1, 1)
        self.activeThreads = QtGui.QLineEdit(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.activeThreads.sizePolicy().hasHeightForWidth())
        self.activeThreads.setSizePolicy(sizePolicy)
        self.activeThreads.setReadOnly(True)
        self.activeThreads.setObjectName(_fromUtf8("activeThreads"))
        self.gridLayout_4.addWidget(self.activeThreads, 0, 4, 1, 1)
        self.runningThreadLabel = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.runningThreadLabel.sizePolicy().hasHeightForWidth())
        self.runningThreadLabel.setSizePolicy(sizePolicy)
        self.runningThreadLabel.setObjectName(_fromUtf8("runningThreadLabel"))
        self.gridLayout_4.addWidget(self.runningThreadLabel, 0, 3, 1, 1)
        self.selectedGameCombo = QtGui.QComboBox(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectedGameCombo.sizePolicy().hasHeightForWidth())
        self.selectedGameCombo.setSizePolicy(sizePolicy)
        self.selectedGameCombo.setObjectName(_fromUtf8("selectedGameCombo"))
        self.gridLayout_4.addWidget(self.selectedGameCombo, 0, 1, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox_2, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.runSync.setText(_translate("MainWindow", "Run FastDownload Sync", None))
        self.groupBox.setTitle(_translate("MainWindow", "Directory Settings", None))
        self.sourceDirBtn.setText(_translate("MainWindow", "Source Directory", None))
        self.sourceDirDisplay.setText(_translate("MainWindow", "d:\\gmod\\garrysmod", None))
        self.destDirBtn.setText(_translate("MainWindow", "FastDL Directory", None))
        self.destDirDisplay.setText(_translate("MainWindow", "d:\\fastdl\\garrysmod", None))
        self.excludeListBtn.setText(_translate("MainWindow", "Select Exclude List", None))
        self.excludeListDisplay.setPlaceholderText(_translate("MainWindow", "Example-Exclude.txt", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Sync Settings", None))
        self.label_2.setText(_translate("MainWindow", "Sync Threads", None))
        self.bZipEnable.setText(_translate("MainWindow", "Bzip", None))
        self.label.setText(_translate("MainWindow", "Selected Game:", None))
        self.activeThreads.setText(_translate("MainWindow", "0", None))
        self.runningThreadLabel.setText(_translate("MainWindow", "Running Threads", None))

